"""esquema inicial del instrumento

ID de revisión: 288fc4b9c21a
Revisión anterior: 
Fecha: 2026-08-24 13:38:51.317064
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision = '288fc4b9c21a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('seudonimo', sa.String(length=32), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuentas'))
    )
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuentas_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_cuentas_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_cuentas_seudonimo'), ['seudonimo'], unique=True)

    op.create_table('instancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('subtema', sa.String(length=120), nullable=True),
    sa.Column('dificultad_declarada', sa.Integer(), nullable=False),
    sa.Column('enunciado_publico', sa.Text(), nullable=False),
    sa.Column('dato_a', sa.Text(), nullable=False),
    sa.Column('dato_b', sa.Text(), nullable=False),
    sa.Column('respuesta_canonica', sa.Text(), nullable=False),
    sa.Column('tipo_respuesta', sa.String(length=20), nullable=False),
    sa.Column('resolucion_latex', sa.Text(), nullable=False),
    sa.Column('estructura_solucion', sa.JSON(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dificultad_declarada BETWEEN 1 AND 5', name=op.f('ck_instancias_dificultad_valida')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instancias')),
    sa.UniqueConstraint('codigo', 'version', name='codigo_version')
    )
    with op.batch_alter_table('instancias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instancias_activa'), ['activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_instancias_area'), ['area'], unique=False)
        batch_op.create_index('ix_instancias_area_activa', ['area', 'activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_instancias_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_instancias_hash_contenido'), ['hash_contenido'], unique=False)

    op.create_table('consentimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('version_texto', sa.String(length=32), nullable=False),
    sa.Column('hash_texto', sa.String(length=64), nullable=False),
    sa.Column('otorgado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retirado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], name=op.f('fk_consentimientos_cuenta_id_cuentas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consentimientos'))
    )
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentimientos_cuenta_id'), ['cuenta_id'], unique=False)

    op.create_table('ejecuciones_solver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instancia_id', sa.Integer(), nullable=False),
    sa.Column('celda', sa.String(length=16), nullable=False),
    sa.Column('indice_replica', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=64), nullable=False),
    sa.Column('esfuerzo', sa.String(length=16), nullable=False),
    sa.Column('huella_experimental', sa.String(length=32), nullable=False),
    sa.Column('respuesta_cruda', sa.Text(), nullable=False),
    sa.Column('respuesta_extraida', sa.Text(), nullable=True),
    sa.Column('veredicto', sa.String(length=20), nullable=False),
    sa.Column('acerto', sa.Boolean(), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('ejecutada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instancia_id'], ['instancias.id'], name=op.f('fk_ejecuciones_solver_instancia_id_instancias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ejecuciones_solver'))
    )
    with op.batch_alter_table('ejecuciones_solver', schema=None) as batch_op:
        batch_op.create_index('ix_ejecuciones_instancia_celda', ['instancia_id', 'celda'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecuciones_solver_acerto'), ['acerto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecuciones_solver_huella_experimental'), ['huella_experimental'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecuciones_solver_instancia_id'), ['instancia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecuciones_solver_veredicto'), ['veredicto'], unique=False)

    op.create_table('episodios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('instancia_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=32), nullable=False),
    sa.Column('condicion_divulgacion', sa.String(length=16), nullable=False),
    sa.Column('lado_humano', sa.String(length=4), nullable=True),
    sa.Column('modelo_participante', sa.String(length=64), nullable=False),
    sa.Column('esfuerzo_participante', sa.String(length=16), nullable=False),
    sa.Column('huella_experimental', sa.String(length=32), nullable=False),
    sa.Column('semilla', sa.Integer(), nullable=False),
    sa.Column('simulado', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('turnos_usados', sa.Integer(), nullable=False),
    sa.Column('respuesta_final', sa.Text(), nullable=True),
    sa.Column('veredicto', sa.String(length=20), nullable=True),
    sa.Column('acerto', sa.Boolean(), nullable=True),
    sa.Column('turno_divulgacion_a', sa.Integer(), nullable=True),
    sa.Column('turno_divulgacion_b', sa.Integer(), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], name=op.f('fk_episodios_cuenta_id_cuentas')),
    sa.ForeignKeyConstraint(['instancia_id'], ['instancias.id'], name=op.f('fk_episodios_instancia_id_instancias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodios'))
    )
    with op.batch_alter_table('episodios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodios_acerto'), ['acerto'], unique=False)
        batch_op.create_index('ix_episodios_analisis', ['modalidad', 'condicion_divulgacion', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_cuenta_id'), ['cuenta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_huella_experimental'), ['huella_experimental'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_instancia_id'), ['instancia_id'], unique=False)
        batch_op.create_index('ix_episodios_instancia_modalidad', ['instancia_id', 'modalidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_modalidad'), ['modalidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_simulado'), ['simulado'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodios_veredicto'), ['veredicto'], unique=False)

    op.create_table('mediciones_diseno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instancia_id', sa.Integer(), nullable=False),
    sa.Column('huella_experimental', sa.String(length=32), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('v_vacia', sa.Float(), nullable=False),
    sa.Column('v_solo_a', sa.Float(), nullable=False),
    sa.Column('v_solo_b', sa.Float(), nullable=False),
    sa.Column('v_ambos', sa.Float(), nullable=False),
    sa.Column('ensayos_por_celda', sa.Integer(), nullable=False),
    sa.Column('interdependencia', sa.Float(), nullable=False),
    sa.Column('balance_carga', sa.Float(), nullable=False),
    sa.Column('emergencia', sa.Float(), nullable=False),
    sa.Column('rondas_minimas', sa.Integer(), nullable=False),
    sa.Column('dificultad', sa.Float(), nullable=False),
    sa.Column('error_estandar_balance', sa.Float(), nullable=True),
    sa.Column('monotonia_violada', sa.Boolean(), nullable=False),
    sa.Column('advertencias', sa.JSON(), nullable=False),
    sa.Column('calculada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instancia_id'], ['instancias.id'], name=op.f('fk_mediciones_diseno_instancia_id_instancias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mediciones_diseno')),
    sa.UniqueConstraint('instancia_id', 'huella_experimental', name='instancia_huella')
    )
    with op.batch_alter_table('mediciones_diseno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediciones_diseno_huella_experimental'), ['huella_experimental'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediciones_diseno_instancia_id'), ['instancia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediciones_diseno_interdependencia'), ['interdependencia'], unique=False)

    op.create_table('codificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episodio_id', sa.Integer(), nullable=False),
    sa.Column('codificador', sa.String(length=64), nullable=False),
    sa.Column('es_humano', sa.Boolean(), nullable=False),
    sa.Column('pasada', sa.Integer(), nullable=False),
    sa.Column('puntajes', sa.JSON(), nullable=False),
    sa.Column('indice_calidad', sa.Float(), nullable=False),
    sa.Column('modalidad_adivinada', sa.String(length=32), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('codificada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episodio_id'], ['episodios.id'], name=op.f('fk_codificaciones_episodio_id_episodios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_codificaciones')),
    sa.UniqueConstraint('episodio_id', 'codificador', 'pasada', name='episodio_codificador')
    )
    with op.batch_alter_table('codificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codificaciones_codificador'), ['codificador'], unique=False)
        batch_op.create_index(batch_op.f('ix_codificaciones_episodio_id'), ['episodio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_codificaciones_es_humano'), ['es_humano'], unique=False)
        batch_op.create_index(batch_op.f('ix_codificaciones_indice_calidad'), ['indice_calidad'], unique=False)

    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episodio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('tipo_autor', sa.String(length=12), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episodio_id'], ['episodios.id'], name=op.f('fk_turnos_episodio_id_episodios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnos')),
    sa.UniqueConstraint('episodio_id', 'orden', name='episodio_orden')
    )
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_episodio_id'), ['episodio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_episodio_id'))

    op.drop_table('turnos')
    with op.batch_alter_table('codificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codificaciones_indice_calidad'))
        batch_op.drop_index(batch_op.f('ix_codificaciones_es_humano'))
        batch_op.drop_index(batch_op.f('ix_codificaciones_episodio_id'))
        batch_op.drop_index(batch_op.f('ix_codificaciones_codificador'))

    op.drop_table('codificaciones')
    with op.batch_alter_table('mediciones_diseno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediciones_diseno_interdependencia'))
        batch_op.drop_index(batch_op.f('ix_mediciones_diseno_instancia_id'))
        batch_op.drop_index(batch_op.f('ix_mediciones_diseno_huella_experimental'))

    op.drop_table('mediciones_diseno')
    with op.batch_alter_table('episodios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodios_veredicto'))
        batch_op.drop_index(batch_op.f('ix_episodios_simulado'))
        batch_op.drop_index(batch_op.f('ix_episodios_modalidad'))
        batch_op.drop_index('ix_episodios_instancia_modalidad')
        batch_op.drop_index(batch_op.f('ix_episodios_instancia_id'))
        batch_op.drop_index(batch_op.f('ix_episodios_huella_experimental'))
        batch_op.drop_index(batch_op.f('ix_episodios_estado'))
        batch_op.drop_index(batch_op.f('ix_episodios_cuenta_id'))
        batch_op.drop_index('ix_episodios_analisis')
        batch_op.drop_index(batch_op.f('ix_episodios_acerto'))

    op.drop_table('episodios')
    with op.batch_alter_table('ejecuciones_solver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejecuciones_solver_veredicto'))
        batch_op.drop_index(batch_op.f('ix_ejecuciones_solver_instancia_id'))
        batch_op.drop_index(batch_op.f('ix_ejecuciones_solver_huella_experimental'))
        batch_op.drop_index(batch_op.f('ix_ejecuciones_solver_acerto'))
        batch_op.drop_index('ix_ejecuciones_instancia_celda')

    op.drop_table('ejecuciones_solver')
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentimientos_cuenta_id'))

    op.drop_table('consentimientos')
    with op.batch_alter_table('instancias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instancias_hash_contenido'))
        batch_op.drop_index(batch_op.f('ix_instancias_codigo'))
        batch_op.drop_index('ix_instancias_area_activa')
        batch_op.drop_index(batch_op.f('ix_instancias_area'))
        batch_op.drop_index(batch_op.f('ix_instancias_activa'))

    op.drop_table('instancias')
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_seudonimo'))
        batch_op.drop_index(batch_op.f('ix_cuentas_rol'))
        batch_op.drop_index(batch_op.f('ix_cuentas_email'))

    op.drop_table('cuentas')
    # ### end Alembic commands ###
